# name 可以自定义
name: Deploy-blog

# 触发条件：在 push 到 main/master 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    # 指定 node 版本
    #    container: node:18.18.2

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      # 生成静态文件
      - name: 构建文档
        # 设置环境变量
        env:
          giscusRepoId: ${{ secrets.GISCUS_REPO_ID }} # giscus 评论插件
          giscusCategoryId: ${{ secrets.GISCUS_CATEGORY_ID }} # giscus 评论插件
          algoliaAppId: ${{secrets.ALGOLIA_APPLICATION_ID}}
          algoliaAppKey: ${{secrets.ALGOLIA_API_KEY}}

        run: |-
          pnpm build
          > src/.vuepress/dist/.nojekyll

      # 部署到 GitHub Pages
      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
          BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
          FOLDER: src/.vuepress/dist # vuepress 生成的静态文件存放的地方
